### ISSUE TITLE
panic: runtime error: index out of range

### ISSUE THREAD

**Issue by sign0** [tidwall/tile38#247]
Hello,

I just migrate to the latest version of tile38 (1.10.0) under docker.

When I make an insert with the redis protocol, I have this error message :

```
2018/01/18 02:16:10 [INFO] Server started, Tile38 version 1.10.0, git 206f499
2018/01/18 02:16:10 [INFO] AOF loaded 0 commands: 0.00s, 0/s, 0 bytes/s
2018/01/18 02:16:10 [INFO] The server is now ready to accept connections on port 9851
panic: runtime error: index out of range

goroutine 147 [running]:
github.com/tidwall/tile38/controller/server.(*PipelineReader).ReadMessages(0xc4205e4000, 0x40, 0x3c, 0x0, 0x0, 0x0)
	/var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/reader.go:227 +0xb3c
github.com/tidwall/tile38/controller/server.handleConn.func2(0xc4205e4000, 0xc42019cb01, 0xc420411f60, 0xc42019caf0, 0xc4202d7cf0, 0xc420152720, 0x0)
	/var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/server.go:118 +0x40
github.com/tidwall/tile38/controller/server.handleConn(0xc420152720, 0xc42018df20, 0xc4202d7cf0, 0xc42018df40, 0xc4202d7d00, 0x1)
	/var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/server.go:161 +0x244
created by github.com/tidwall/tile38/controller/server.ListenAndServe
	/var/folders/vd/jr9h6jyj1n34s5nsphy6y88m0000gn/T/tile38.XXXX.ErlUHtAz/go/src/github.com/tidwall/tile38/controller/server/server.go:80 +0x29a
```
Step to reproduce :

Here is my docker-compose :
```
tile38:
    image: tile38/tile38
    volumes:
      - ./data/tictac_tile38:/data
    ports:
    - "9851: 9851"
```

I also tried with ```chmod -R 777 ./data/tictac_tile38 -R && chown -R tile38:tile38 ./data/tictac_tile38```

I'm using the client ```redis-cli --pipe``` installed on a node:boron image with ```apt-get install -y redis-cli``` (my code work with a classical instance of tile38 v1.9.1)

I do not really know what to do ... An idea ? :)

Thanks

**Comment by tidwall** [comment]
This issue was raised a couple days ago. #246 
I just pushed a new release v1.10.1 that fixes this problem. Please let me know if you still have problems. Thanks!

**Comment by sign0** [comment]
Nice, thanks for your quick reply !
I test this in the evening..
