### ISSUE TITLE
WITHIN Command Problem

### ISSUE THREAD

**Issue by robmir44** [tidwall/tile38#337]
hello,

I have created a command via Interface (Java):

```
@Command("WITHIN ?0 FENCE DETECT inside,outside POINTS BOUNDS ?1 ?2 ?3 ?4")
    List<Object> withinDetection(String key, double southwesternLon, double southwesternLat, double northeasternLon, double  northeasternLat);

```
But if I call the command then I get an exception (see below)
`List<Object> resultListWithinDetection = commands.withinDetection("fleet", 28.98, 22.001624, 59.103432, 22.201624);
`
```
Exception in thread "main" io.lettuce.core.RedisException: java.lang.NullPointerException
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:88)
	at io.lettuce.core.LettuceFutures.awaitAll(LettuceFutures.java:46)
	at io.lettuce.core.dynamic.AsyncExecutableCommand.dispatchCommand(AsyncExecutableCommand.java:81)
	at io.lettuce.core.dynamic.AsyncExecutableCommand.execute(AsyncExecutableCommand.java:53)
	at io.lettuce.core.dynamic.RedisCommandFactory$CommandFactoryExecutorMethodInterceptor.invoke(RedisCommandFactory.java:227)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain$MethodInterceptorContext.proceed(MethodInterceptorChain.java:117)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain$PooledMethodInvocation.proceed(MethodInterceptorChain.java:194)
	at io.lettuce.core.dynamic.intercept.DefaultMethodInvokingInterceptor.invoke(DefaultMethodInvokingInterceptor.java:45)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain$MethodInterceptorContext.proceed(MethodInterceptorChain.java:117)
	at io.lettuce.core.dynamic.intercept.MethodInterceptorChain.invoke(MethodInterceptorChain.java:79)
	at io.lettuce.core.dynamic.intercept.InvocationProxyFactory$InterceptorChainInvocationHandler.handleInvocation(InvocationProxyFactory.java:101)
	at io.lettuce.core.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at cloud.continental.cfsp.damagereportservice.$Proxy7.withinDetection(Unknown Source)
```
Could anybody tell me what is the Problem? 

FYI. I used here dummy coordinates

**Comment by tidwall** [comment]
Hi,

I don't think that the lettuce client allows for live geofences, which are raw tcp streams of [JSON lines](http://jsonlines.org/). 

If you need a raw tcp stream of geofence notifications using Java, then I recommend connecting directly to the Tile38 server with the Socket object.

Otherwise you can use the SETHOOK and bind to an endpoint.

**Comment by robmir44** [comment]
Hi, Thanks for the answer.
With python it seems to work. I tried the WITHIN command and it's a little strange for me, because I also got "Points", which were positioned on the border. I thought that I will get Points as result, which are inside the bounds and with INTERSECTS all Points, which are inside and on border of an area.

**Comment by tidwall** [comment]
There's now support for Redis style Pub/Sub using the [`SETCHAN`](https://tile38.com/commands/setchan/) command. This will allow for subscribing to a geofence using lettuce.
