### ISSUE TITLE
IllegalStateException with SETCHAN custom command (java lettuce client)

### ISSUE THREAD

**Issue by mohamedimli** [tidwall/tile38#452]
Hi,
SETCHAN is not listed in commands enum, i decide to imlements it by using this code snippet 👍 

`public enum CustomCommandType implements ProtocolKeyword {

    SETCHAN;

    public final byte[] bytes;

    private CustomCommandType() {
        this.bytes = this.name().getBytes(LettuceCharsets.ASCII);
    }

    @Override
    public byte[] getBytes() {
        return this.bytes;
    }
}
`  
And use it like this:

`       sync.dispatch(CustomCommandType.SETCHAN,
                            new StatusOutput<>(codec), new CommandArgs<>(codec)
                                    .add(channel)
                                    .add("WITHIN")
                                    .add("drivers")
                                    .add("FENCE")
                                    .add("OBJECT")
                                    .add(stringGeoJson));`

But I get this Exception : 

`Exception in thread "main" com.lambdaworks.redis.RedisException: java.lang.IllegalStateException
	at com.lambdaworks.redis.LettuceFutures.await(LettuceFutures.java:124)
	at com.lambdaworks.redis.LettuceFutures.awaitOrCancel(LettuceFutures.java:92)
	at com.lambdaworks.redis.FutureSyncInvocationHandler.handleInvocation(FutureSyncInvocationHandler.java:63)
	at com.lambdaworks.redis.internal.AbstractInvocationHandler.invoke(AbstractInvocationHandler.java:80)
	at com.sun.proxy.$Proxy0.dispatch(Unknown Source)
	at com.imli.App.main(App.java:115)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at com.intellij.rt.execution.application.AppMain.main(AppMain.java:147)
Caused by: java.lang.IllegalStateException`

Any help please ?

**Comment by tidwall** [comment]
Hi @mohamedimli 

On the surface, your Tile38 command syntax looks fine. I wish I could help you out with the Java side, but I'm not familiar too familiar with the lettuce custom command interface.

Here're some links that touch on using Tile38 with lettuce. Forgive me if you've already seen these:

https://stackoverflow.com/questions/48576291/redis-lettuce-sending-custom-commands
https://github.com/lettuce-io/lettuce-core/issues/811
https://github.com/tidwall/tile38/wiki/Java-example-(lettuce)

**Comment by pacocastamar** [comment]
You can't use lettuce using setchan because you can't suscribe using redis endpoint. I imagine thats why setchan is not a part of the commands. Even though you try to create your own it will not work.

The options are use the websockets interface or the http.

Regards

**Comment by tidwall** [comment]
Actually, you should be able subscribe to a Tile38 channel from any redis compatible client.

For example, below I use the standard `redis-cli` to create a geofence channel using the SETCHAN command. In a different terminal I subscribe to the channel in the same way as you would subscribe to any Redis channel. Finally I send Tile38 some SET POINT commands, which fire off notifications to the the channel.

![setchan](https://user-images.githubusercontent.com/1156077/62416515-1a082d00-b5f1-11e9-83b1-3d2580bbad3c.gif)

**Comment by pacocastamar** [comment]
Kind of interesting. Tried that with lettuce on java, and didn't work. Got an Illegal state exception. I'll try with redis later on and let you know what happens...

**Comment by pacocastamar** [comment]
Ok, found that it works Tidwall, it was just a matter of using the right CommandOutput (BTW I kept using lettuce). The key was that the return for setchan command was an integer, not an "ok", therefore the StatusOutput wasn't applicable. 

And yes, you were also right about subscription.

Owe you a beer!!!!

**Comment by LUOrenjia** [comment]
try this:
```
RedisClient client = RedisClient.create("redis://********:9851");
StatefulRedisPubSubConnection<String, String> connection = client.connectPubSub();
RedisPubSubCommands<String, String> sync = connection.sync();
StringCodec codec = StringCodec.ASCII;

sync.dispatch(CustomCommandType.SETCHAN,
            new PubSubOutput<>(codec), 
            new CommandArgs<>(codec)
            .add(channel)
            .add("WITHIN")
            .add("drivers")
            .add("FENCE")
            .add("OBJECT")
            .add(stringGeoJson));
```
