### ISSUE TITLE
Fatal panic on concurrent write in stats.go under heavy load

### ISSUE THREAD

**Issue by saltatory** [tidwall/tile38#485]
I wrote a load test for a websocket server that is accessing Tile38. The client is using the Tile38 NodeJS client. The client is generating a LOT of FENCE queries, closing them, and generating new fence queries. Eventually, under enough load (something like 400 fence notifications/s), the server reliably dies.

In the affected code, the offending line appears to be where `writeInfoReplication` is accessing the list of current connections `c.conns`. These connections are changing rapidly under load and therefore appear to be generating a concurrent access exception.

The top of the stack trace (because there are so many active go routines) :
```bash
[32mtile38_1      |[0m fatal error: concurrent map iteration and map write
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 1618 [running]:
[32mtile38_1      |[0m runtime.throw(0xcec8ea, 0x26)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/panic.go:608 +0x72 fp=0xc000c9ace8 sp=0xc000c9acb8 pc=0x42c2d2
[32mtile38_1      |[0m runtime.mapiternext(0xc000c9ae58)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/map.go:790 +0x525 fp=0xc000c9ad70 sp=0xc000c9ace8 pc=0x40ed75
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).writeInfoReplication(0xc000310000, 0xc00014fdc0)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/stats.go:368 +0x103 fp=0xc000c9aec8 sp=0xc000c9ad70 pc=0xb04e33
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).cmdInfo(0xc000310000, 0xc0011241e0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/stats.go:427 +0xaa0 fp=0xc000c9b118 sp=0xc000c9aec8 pc=0xb05d60
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).command(0xc000310000, 0xc0011241e0, 0xc003400000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:1006 +0x15ba fp=0xc000c9d5a8 sp=0xc000c9b118 pc=0xaf92fa
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).handleInputCommand.func4(0xc0011241e0, 0xc003b78f00, 0xc001d28060, 0xc000310000, 0xc003400000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:875 +0x184 fp=0xc000c9d970 sp=0xc000c9d5a8 pc=0xb1ffc4
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).handleInputCommand(0xc000310000, 0xc003400000, 0xc0011241e0, 0x0, 0x0)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:876 +0x94c fp=0xc000c9de08 sp=0xc000c9d970 pc=0xaf5a9c
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).netServe.func1(0xc00058e368, 0xc000310000, 0xe23c60, 0xc00012e540)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:414 +0x490 fp=0xc000c9dfc0 sp=0xc000c9de08 pc=0xb1dfe0
[32mtile38_1      |[0m runtime.goexit()
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000c9dfc8 sp=0xc000c9dfc0 pc=0x45c3c1
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.(*Server).netServe
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:318 +0x21f
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 1 [IO wait]:
[32mtile38_1      |[0m internal/poll.runtime_pollWait(0x7fdeeb13bf00, 0x72, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/netpoll.go:173 +0x66
[32mtile38_1      |[0m internal/poll.(*pollDesc).wait(0xc000854998, 0x72, 0xc000404900, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
[32mtile38_1      |[0m internal/poll.(*pollDesc).waitRead(0xc000854998, 0xffffffffffffff00, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
[32mtile38_1      |[0m internal/poll.(*FD).Accept(0xc000854980, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/internal/poll/fd_unix.go:384 +0x1a0
[32mtile38_1      |[0m net.(*netFD).accept(0xc000854980, 0xc00009a6e8, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/net/fd_unix.go:238 +0x42
[32mtile38_1      |[0m net.(*TCPListener).accept(0xc00043c018, 0xc00068b960, 0xc00068b968, 0x20)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/net/tcpsock_posix.go:139 +0x2e
[32mtile38_1      |[0m net.(*TCPListener).Accept(0xc00043c018, 0xd0d470, 0xc00058e368, 0xc000310000, 0xe23c60)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/net/tcpsock.go:260 +0x47
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).netServe(0xc000310000, 0x0, 0x0)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:313 +0x233
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.Serve(0x0, 0x0, 0x267b, 0x7fffc8ce0f72, 0x5, 0x1, 0x0, 0x0)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:287 +0xb34
[32mtile38_1      |[0m main.main()
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/cmd/tile38-server/main.go:413 +0x21b8
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 33 [syscall, 1 minutes]:
[32mtile38_1      |[0m os/signal.signal_recv(0x6c2433)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
[32mtile38_1      |[0m os/signal.loop()
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
[32mtile38_1      |[0m created by os/signal.init.0
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/os/signal/signal_unix.go:29 +0x41
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 49 [chan receive, 1 minutes]:
[32mtile38_1      |[0m main.main.func6(0xc000122720, 0xc0002b0240, 0xc0002b0220)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/cmd/tile38-server/main.go:371 +0x41
[32mtile38_1      |[0m created by main.main
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/cmd/tile38-server/main.go:370 +0x1f42
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 50 [sleep]:
[32mtile38_1      |[0m time.Sleep(0x3b9aca00)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/time.go:105 +0x14f
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/endpoint.(*Manager).Run(0xc00030e210)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/endpoint/endpoint.go:139 +0x2a
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/endpoint.NewManager
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/endpoint/endpoint.go:132 +0x93
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 51 [chan receive]:
[32mtile38_1      |[0m github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.(*DB).backgroundManager(0xc00041c0b0)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:548 +0xee
[32mtile38_1      |[0m created by github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.Open
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:171 +0x307
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 81 [sync.Cond.Wait]:
[32mtile38_1      |[0m sync.runtime_notifyListWait(0xc0003020d0, 0xc0000000a7)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/sema.go:510 +0xeb
[32mtile38_1      |[0m sync.(*Cond).Wait(0xc0003020c0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/sync/cond.go:56 +0x92
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).processLives(0xc000310000)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/live.go:44 +0x300
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.Serve
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:269 +0xa41
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 82 [chan receive]:
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).watchOutOfMemory(0xc000310000)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:561 +0x112
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.Serve
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:270 +0xa66
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 83 [chan receive]:
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).watchLuaStatePool(0xc000310000)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:585 +0xb6
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.Serve
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:271 +0xa8b
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 84 [chan receive]:
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).watchAutoGC(0xc000310000)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:530 +0xff
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.Serve
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:272 +0xab0
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 85 [sleep]:
[32mtile38_1      |[0m time.Sleep(0x5f5e100)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/time.go:105 +0x14f
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).backgroundExpiring(0xc000310000)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/expire.go:156 +0x497
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.Serve
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:273 +0xad5
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 86 [chan receive]:
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).backgroundSyncAOF(0xc000310000)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:596 +0x9e
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.Serve
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:274 +0xafa
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 88 [IO wait]:
[32mtile38_1      |[0m internal/poll.runtime_pollWait(0x7fdeeb13be30, 0x72, 0xc002553ce8)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/netpoll.go:173 +0x66
[32mtile38_1      |[0m internal/poll.(*pollDesc).wait(0xc000854a18, 0x72, 0xffffffffffffff00, 0xe16ec0, 0x13664e8)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:85 +0x9a
[32mtile38_1      |[0m internal/poll.(*pollDesc).waitRead(0xc000854a18, 0xc00081c000, 0xffff, 0xffff)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/internal/poll/fd_poll_runtime.go:90 +0x3d
[32mtile38_1      |[0m internal/poll.(*FD).Read(0xc000854a00, 0xc00081c000, 0xffff, 0xffff, 0x0, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/internal/poll/fd_unix.go:169 +0x179
[32mtile38_1      |[0m net.(*netFD).Read(0xc000854a00, 0xc00081c000, 0xffff, 0xffff, 0x2404, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/net/fd_unix.go:202 +0x4f
[32mtile38_1      |[0m net.(*conn).Read(0xc00043c028, 0xc00081c000, 0xffff, 0xffff, 0x0, 0x0, 0x0)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/net/net.go:177 +0x68
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).netServe.func1(0xc00058e368, 0xc000310000, 0xe23c60, 0xc00043c028)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:365 +0x58f
[32mtile38_1      |[0m created by github.com/tidwall/tile38/internal/server.(*Server).netServe
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/server.go:318 +0x21f
[32mtile38_1      |[0m 
[32mtile38_1      |[0m goroutine 1417 [sync.Cond.Wait]:
[32mtile38_1      |[0m sync.runtime_notifyListWait(0xc000fb4910, 0x19)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/runtime/sema.go:510 +0xeb
[32mtile38_1      |[0m sync.(*Cond).Wait(0xc000fb4900)
[32mtile38_1      |[0m 	/home/travis/.gimme/versions/go1.11.11.linux.amd64/src/sync/cond.go:56 +0x92
[32mtile38_1      |[0m github.com/tidwall/tile38/internal/server.(*Server).goLive(0xc000310000, 0xe16320, 0xc000fbe000, 0xe239c0, 0xc0004eab40, 0xc003310040, 0xc002ac5680, 0xc003310000, 0x0, 0x0)
[32mtile38_1      |[0m 	/tmp/tile38.Wzcq/go/src/github.com/tidwall/tile38/internal/server/live.go:200 +0xadc
```

**Comment by tidwall** [comment]
Does PR #486 fix this issue?

**Comment by saltatory** [comment]
Yup. Sorry I left it open!
