### ISSUE TITLE
fatal error: concurrent map read and map write - after service restart

### ISSUE THREAD

**Issue by belek** [tidwall/tile38#497]
We activly use geofences with web hooks and after restarting Tile38 it crashes with fatal error. Only after removing appendonly.aof file the service starts properly.

```
tile38_1               |    _______ _______
tile38_1               |   |       |       |
tile38_1               |   |____   |   _   |   Tile38 1.17.6 (93cf63f) 64 bit (amd64/linux)
tile38_1               |   |       |       |   Port: 9851, PID: 1
tile38_1               |   |____   |   _   | 
tile38_1               |   |       |       |   tile38.com
tile38_1               |   |_______|_______| 
tile38_1               | 
tile38_1               | 2019/10/08 05:56:22 [INFO] Server started, Tile38 version 1.17.6, git 93cf63f
tile38_1               | 2019/10/08 05:56:22 [DEBU] Geom indexing: QuadTree (64 points)
tile38_1               | 2019/10/08 05:56:22 [DEBU] Multi indexing: RTree (64 points)
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop120_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop120_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop120_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop155_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop155_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop155_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop158_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop158_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop158_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop161_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop161_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop161_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop174_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop174_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop174_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop183_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop184_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop184_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop184_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop185_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop185_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop185_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop187_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop187_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop187_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop205_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop205_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12301bus_stop205_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop108_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop108_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop105_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop108_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop110_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop112_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop112_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop112_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop114_destination
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop114_small
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop114_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop143_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop173_small_cross
tile38_1               | 2019/10/08 05:56:22 [DEBU] purged hook trip12505bus_stop196_destination
tile38_1               | fatal error: concurrent map read and map write
tile38_1               | 
tile38_1               | goroutine 87 [running]:
tile38_1               | runtime.throw(0xcf0735, 0x21)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/panic.go:608 +0x72 fp=0xc000176c08 sp=0xc000176bd8 pc=0x42c2d2
tile38_1               | runtime.mapaccess2_faststr(0xbdc0c0, 0xc000138210, 0xc000034c40, 0x1a, 0x1, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/map_faststr.go:110 +0x458 fp=0xc000176c78 sp=0xc000176c08 pc=0x412588
tile38_1               | github.com/tidwall/tile38/internal/server.(*Server).possiblyExpireHook(0xc000310000, 0xc000034c40, 0x1a)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:320 +0xb4 fp=0xc000176f68 sp=0xc000176c78 pc=0xad6374
tile38_1               | github.com/tidwall/tile38/internal/server.Serve.func1(0xe1d360, 0xc00001b800)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/server.go:161 +0x6c fp=0xc000176f90 sp=0xc000176f68 pc=0xb248bc
tile38_1               | github.com/tidwall/tile38/internal/expire.(*List).bg(0xc000310250)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/expire/expire.go:46 +0x11a fp=0xc000176fd8 sp=0xc000176f90 pc=0xaad5aa
tile38_1               | runtime.goexit()
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/asm_amd64.s:1333 +0x1 fp=0xc000176fe0 sp=0xc000176fd8 pc=0x45c3c1
tile38_1               | created by github.com/tidwall/tile38/internal/expire.(*List).Push
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/expire/expire.go:27 +0x115
tile38_1               | 
tile38_1               | goroutine 1 [runnable]:
tile38_1               | github.com/tidwall/tile38/vendor/github.com/tidwall/geojson.makeCircleObject(0x405aae7ecfe9b7bf, 0x4025786ec17ebaf1, 0x4059000000000000, 0x40, 0xd4dc0ebdd5175f68, 0xd400000027087581)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/geojson/circle.go:254 +0x51b
tile38_1               | github.com/tidwall/tile38/vendor/github.com/tidwall/geojson.(*Circle).getObject(0xc0004a1310, 0x48f456, 0xc000343d60)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/geojson/circle.go:223 +0x70
tile38_1               | github.com/tidwall/tile38/vendor/github.com/tidwall/geojson.(*Circle).Rect(0xc0004a1310, 0xc00046cdb0, 0xcdbf3c, 0x7, 0x13df480)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/geojson/circle.go:211 +0x2b
tile38_1               | github.com/tidwall/tile38/internal/server.(*Server).cmdSetHook(0xc000310000, 0xc0004a12c0, 0xcdc200, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:202 +0x174d
tile38_1               | github.com/tidwall/tile38/internal/server.(*Server).command(0xc000310000, 0xc0004a12c0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/server.go:951 +0x3e9e
tile38_1               | github.com/tidwall/tile38/internal/server.(*Server).loadAOF(0xc000310000, 0x0, 0x0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/aof.go:91 +0x2d6
tile38_1               | github.com/tidwall/tile38/internal/server.Serve(0x0, 0x0, 0x267b, 0x7ffd37b1ff72, 0x5, 0x1, 0x0, 0x0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/server.go:254 +0xc99
tile38_1               | main.main()
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/cmd/tile38-server/main.go:413 +0x21b8
tile38_1               | 
tile38_1               | goroutine 33 [syscall]:
tile38_1               | os/signal.signal_recv(0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sigqueue.go:139 +0x9c
tile38_1               | os/signal.loop()
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/signal/signal_unix.go:23 +0x22
tile38_1               | created by os/signal.init.0
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/os/signal/signal_unix.go:29 +0x41
tile38_1               | 
tile38_1               | goroutine 49 [chan receive]:
tile38_1               | main.main.func6(0xc000144660, 0xc0002c8220, 0xc0002c8200)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/cmd/tile38-server/main.go:371 +0x41
tile38_1               | created by main.main
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/cmd/tile38-server/main.go:370 +0x1f42
tile38_1               | 
tile38_1               | goroutine 50 [sleep]:
tile38_1               | time.Sleep(0x3b9aca00)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/time.go:105 +0x14f
tile38_1               | github.com/tidwall/tile38/internal/endpoint.(*Manager).Run(0xc0001383c0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/endpoint/endpoint.go:139 +0x2a
tile38_1               | created by github.com/tidwall/tile38/internal/endpoint.NewManager
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/endpoint/endpoint.go:132 +0x93
tile38_1               | 
tile38_1               | goroutine 4 [chan receive]:
tile38_1               | github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.(*DB).backgroundManager(0xc0004140b0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:548 +0xee
tile38_1               | created by github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb.Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/vendor/github.com/tidwall/buntdb/buntdb.go:171 +0x307
tile38_1               | 
tile38_1               | goroutine 82 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024e8d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024e8c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001a480)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 96 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024eed0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024eec0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001b440)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 99 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f050, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f040)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001b800)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 100 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f0d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f0c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001b980)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 101 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f150, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f140)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001bb00)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 102 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f1d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f1c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001bbc0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 103 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f250, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f240)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001bd40)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 104 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f2d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f2c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00001bec0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 105 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f350, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f340)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c0c0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 106 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f3d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f3c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c180)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 107 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f450, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f440)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c300)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 108 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f4d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f4c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c480)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 109 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f550, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f540)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c540)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 110 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f5d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f5c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c6c0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 111 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f650, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f640)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c840)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 112 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f6d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f6c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048c9c0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 113 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f750, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f740)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048ca80)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 114 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f7d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f7c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048cc00)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 115 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f850, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f840)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048cd80)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 116 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f8d0, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f8c0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048ce40)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 117 [sync.Cond.Wait]:
tile38_1               | sync.runtime_notifyListWait(0xc00024f950, 0x0)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/runtime/sema.go:510 +0xeb
tile38_1               | sync.(*Cond).Wait(0xc00024f940)
tile38_1               | 	/home/travis/.gimme/versions/go1.11.13.linux.amd64/src/sync/cond.go:56 +0x92
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048cfc0)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:599 +0xb9
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
tile38_1               | 
tile38_1               | goroutine 118 [runnable]:
tile38_1               | github.com/tidwall/tile38/internal/server.(*Hook).manager(0xc00048d140)
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:573
tile38_1               | created by github.com/tidwall/tile38/internal/server.(*Hook).Open
tile38_1               | 	/tmp/tile38.nJrE/go/src/github.com/tidwall/tile38/internal/server/hooks.go:540 +0x136
```

**Comment by tidwall** [comment]
I can see where the data race was happening and I pushed a fix.
