### ISSUE TITLE
GET HASH above 12 will crash the server

### ISSUE THREAD

**Issue by tidwall** [tidwall/tile38#601]
**Describe the bug**
Returning geohash values above 12 will cause a panic

**To Reproduce**

```
SET col obj1 POINT 33 -112
GET col obj1 HASH 13
```

**Expected behavior**

The `GET col obj1 HASH 13` command should return an invalid argument error. 
The same error as you would get from `GET col obj1 HASH 0`

**Logs**
```
2021/03/18 15:45:21 [INFO] Server started, Tile38 version 1.19.5, git 0490734
2021/03/18 15:45:21 [INFO] AOF loaded 18 commands: 0.00s, 98782/s, 7 MB/s
2021/03/18 15:45:21 [INFO] Ready to accept connections at [::]:9851
panic: runtime error: slice bounds out of range [18446744073709551615:12]

goroutine 6 [running]:
github.com/mmcloughlin/geohash.EncodeWithPrecision(0x4040800000000000, 0xc05c000000000000, 0xd, 0x40, 0xd)
	/private/tmp/tile38-20200213-45389-1c8n64y/.brew_home/go/pkg/mod/github.com/mmcloughlin/geohash@v0.0.0-20181009053802-f7f2bcae3294/geohash.go:36 +0xd0
github.com/tidwall/tile38/internal/server.(*Server).cmdGet(0xc00026ac80, 0xc0003de0a0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/tile38-20200213-45389-1c8n64y/internal/server/crud.go:229 +0x1ddd
github.com/tidwall/tile38/internal/server.(*Server).command(0xc00026ac80, 0xc0003de0a0, 0xc000410000, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/tile38-20200213-45389-1c8n64y/internal/server/server.go:1026 +0x3ef
github.com/tidwall/tile38/internal/server.(*Server).handleInputCommand.func4(0xc0003de0a0, 0xc000434000, 0xc0001259f0, 0xc00026ac80, 0xc000410000, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
	/private/tmp/tile38-20200213-45389-1c8n64y/internal/server/server.go:884 +0x302
github.com/tidwall/tile38/internal/server.(*Server).handleInputCommand(0xc00026ac80, 0xc000410000, 0xc0003de0a0, 0x0, 0x0)
	/private/tmp/tile38-20200213-45389-1c8n64y/internal/server/server.go:885 +0x98c
github.com/tidwall/tile38/internal/server.(*Server).netServe.func1(0xc000138540, 0xc00026ac80, 0x1b1b100, 0xc000010028)
	/private/tmp/tile38-20200213-45389-1c8n64y/internal/server/server.go:411 +0x478
created by github.com/tidwall/tile38/internal/server.(*Server).netServe
	/private/tmp/tile38-20200213-45389-1c8n64y/internal/server/server.go:316 +0x235
```

**Operating System (please complete the following information):**
 - OS: Mac OS
 - Version 1.19.5

**Comment by tidwall** [comment]
Never mind. 🤦‍♂️ This was already fixed in 9202fd02
